# Generated by Django 3.1.1 on 2020-09-24 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200919_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deleted',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='inventory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='api.inventory'),
        ),
        migrations.AddField(
            model_name='task',
            name='animals',
            field=models.ManyToManyField(to='api.Animal'),
        ),
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.company'),
        ),
        migrations.AddField(
            model_name='task',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='inventory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.inventory'),
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('animal', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.animal')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='expenses',
            field=models.ManyToManyField(to='api.Expense'),
        ),
    ]
