# Generated by Django 3.1.1 on 2020-09-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='membership',
            new_name='subscription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
