# Generated by Django 3.1.1 on 2020-10-05 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200930_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expenses',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='inventory',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='api.inventory'),
        ),
    ]
