# Generated by Django 3.1.1 on 2020-10-07 17:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201005_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_date',
            new_name='task_due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='animal_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='BreedingSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('animal_semen', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_to', to='api.animal')),
                ('female', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mother_to', to='api.animal')),
                ('inventory_semen', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bred_with', to='api.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='breeding_sets',
            field=models.ManyToManyField(to='api.BreedingSet'),
        ),
    ]
