# Generated by Django 3.1.1 on 2020-10-10 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201008_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='animal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='api.animal'),
        ),
    ]
