# Generated by Django 3.1.1 on 2020-10-10 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_invoiceitem_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='animal',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='api.animal'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='inventory',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='api.inventory'),
        ),
    ]
