# Generated by Django 3.1.1 on 2020-10-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201010_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
