# Generated by Django 3.1.1 on 2020-10-14 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_sale_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='father_placeholder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='mother_placeholder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='father',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sire', to='api.animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='mother',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dam', to='api.animal'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='father',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_of', to='api.animal'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='mother',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_of', to='api.animal'),
        ),
    ]
