# Generated by Django 3.1.1 on 2020-10-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_animal_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='header_image',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='profile_image',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
