# Generated by Django 3.1.1 on 2020-10-30 00:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20201022_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='sold',
            new_name='deleted',
        ),
        migrations.AddField(
            model_name='inventory',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted', models.BooleanField(default=False)),
                ('transferred', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('sale', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='api.sale')),
            ],
        ),
    ]
